# Generated by Django 4.1 on 2023-05-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0002_remove_image_uploaded_at_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
