# Generated by Django 4.1 on 2023-05-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0003_remove_image_name_image_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploaded_at',
        ),
    ]
