# Generated by Django 4.1 on 2023-05-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0006_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='file',
        ),
    ]
