# Generated by Django 4.1 on 2024-02-22 06:38

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creation_time',
            field=models.IntegerField(auto_created=True, default=time.time),
        ),
    ]
